name: my_wallet_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Adicione o fl_chart aqui, dentro de dependencies
  fl_chart: ^0.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/
